### ISSUE TITLE
Win

### ISSUE THREAD

**Issue by jeancarlos1111** [arifikhsan/batu-gunting-kertas-nuxt#15]
![Captura de pantalla de 2021-11-07 13-29-04](https://user-images.githubusercontent.com/10359567/140655290-fbb32ee0-22e2-4b62-8ce4-9a8d46d75424.png)

**Comment by jeancarlos1111** [comment]
Thank you very much for that demo, I admire what you have created

**Comment by kodejuice** [comment]
![Screenshot_20220811-201903_Opera](https://user-images.githubusercontent.com/9017620/184221845-67409bb4-0f5b-4e85-9666-633e5a23033b.jpg)

**Comment by arifikhsan** [comment]
wow very nicee 🎉🎉🎉🎉

**Comment by arifikhsan** [comment]
> 

glad you like it. this is possible because the help of friends and contributors 😇
