### ISSUE TITLE
i'm too good first try baby

### ISSUE THREAD

**Issue by cosmo-root** [arifikhsan/batu-gunting-kertas-nuxt#18]
![chrome_RfmnltrPN4](https://user-images.githubusercontent.com/85837650/194760819-64a88583-6c0c-40e3-85af-39e1a32c3874.png)

**Comment by cosmo-root** [comment]
![chrome_eZlqt3sEVk](https://user-images.githubusercontent.com/85837650/194760937-adbabdd5-a837-4ac6-9d1b-1d84850b2c73.png)

**Comment by arifikhsan** [comment]
i'm afraid of your luck 😁
