### ISSUE TITLE
paper and scissors is mixed up

### ISSUE THREAD

**Issue by MartinMuzatko** [arifikhsan/batu-gunting-kertas-nuxt#2]
https://github.com/arifikhsan/batu-gunting-kertas-nuxt/blob/master/pages/index.vue#L81-L98

https://github.com/arifikhsan/batu-gunting-kertas-nuxt/blob/master/pages/index.vue#L274-L289

**Comment by arifikhsan** [comment]
Hi, could you explain what's wrong?

**Comment by MartinMuzatko** [comment]
When I choose paper, it chooses scissor for me.
When I choose scissor, it chooses paper for me.
Rock is fine.

![rps](https://user-images.githubusercontent.com/2950505/92385836-e3b1b100-f112-11ea-9f9b-89d56b6a7dc2.gif)

Here the function defines 2 as scissors, 3 as paper
https://github.com/arifikhsan/batu-gunting-kertas-nuxt/blob/master/pages/index.vue#L274-L289

Here you use the wrong translations for the wrong numbers :)
https://github.com/arifikhsan/batu-gunting-kertas-nuxt/blob/master/pages/index.vue#L81-L98

**Comment by arifikhsan** [comment]
wow good catch. i dont realize it at all 🎉

**Comment by arifikhsan** [comment]
fixed!
