### ISSUE TITLE
Rock beats paper, scissors beats rock, paper beats scissors

### ISSUE THREAD

**Issue by abhaybd** [arifikhsan/batu-gunting-kertas-nuxt#3]
It seems all the win relationships between the options are reversed.

![image](https://user-images.githubusercontent.com/22180942/92669271-e99bc380-f2c5-11ea-9953-1d496516e644.png)
![image](https://user-images.githubusercontent.com/22180942/92669294-fb7d6680-f2c5-11ea-97dc-7aa80fbbd35a.png)
![image](https://user-images.githubusercontent.com/22180942/92669302-0506ce80-f2c6-11ea-9593-0c438253336f.png)

**Comment by arifikhsan** [comment]
nice, i dont remember when this is happened

**Comment by arifikhsan** [comment]
Thanks!
